[test]

coverage = true

coverageSkipTestFiles = true

coveragePathIgnorePatterns = [
    "lib/defaults/*.ts",
    "test/utils/*.ts",
    "dist/**/*.js",
    "dist/**/*.ts",
    "../**/*.ts",
    "../**/*.js"
]



[test.reporter]
junit = "junit.xml"